server {
  listen       80 default_server;
  server_name  _;

  location / {
    root /var/www/public;

    autoindex on;
    autoindex_exact_size on;
    autoindex_localtime on;
  }

  location /uploads/ {
    root /var/www/public;

    autoindex on;
    autoindex_exact_size on;
    autoindex_localtime on;

    dav_methods PUT;
    dav_access user:rw group:rw all:r;
    client_max_body_size 100m;
  }

  location = /up {
    default_type text/html;
    alias /etc/nginx/upload.html;
  }
}
